Skillet/codewars/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^',include('login.urls',namespace = "login")),
    url(r'^',include('quiz.urls',namespace = "quiz")),
    url(r'^code/',include('coding.urls',namespace = "code")),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Skillet/coding/urls.py
from django.conf.urls import url

from . import views

app_name = 'code'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/(?P<question>[0-9]+)/$',views.submission, name='submission'),
]

Skillet/quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$',views.ans, name='ans'),
    url(r'^(?P<pk>[0-9]+)/disp/$',views.disp, name='disp'),
    url(r'^(?P<pk>[0-9]+)/end/$',views.end, name='end'),
    url(r'^rules/$',views.rules, name = 'rule'),
    url(r'^pop/$',views.s_pop, name = 'pop'),
    url(r'^timer$',views.timer),
]

Skillet/coding/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from quiz.models import Question

# Create your models here.

class CodeManager(models.Manager):
	def get_queryset(self):
		return super(CodeManager,self).get_queryset().filter(type='code')

class CodeQuestion(Question):
	objects = CodeManager()

	class Meta:
		verbose_name = 'Coding Question'
		verbose_name_plural = 'Coding Questions'
		proxy = True

class CodeTestCase(models.Model):
	question = models.ForeignKey(CodeQuestion,on_delete= models.CASCADE)
	input = models.TextField()
	output = models.TextField()

class CodeQuestionExtend(models.Model):
	question = models.OneToOneField(CodeQuestion,on_delete= models.CASCADE)
	problem_statement = models.TextField()
	input_statement = models.TextField()
	output_statement = models.TextField()
	constraint = models.TextField()
	explanation = models.TextField() 
	testcase_file = models.FileField(upload_to='testcases')
	answer_file = models.FileField(upload_to='answers')
	lines_per_testcase = models.IntegerField(default=1)
	lines_per_answer = models.IntegerField(default=1)

class CodeUserStatus(models.Model):
	User = models.ForeignKey(User)
	question = models.ForeignKey(CodeQuestion)
	status = (
		('Accepted','Accepted'),
		('Not Accepted','Not Accepted'),
		)
	question_status = models.CharField(max_length=15,choices=status,default='Not Accepted')
	remaining_time = models.IntegerField(blank=True,null=True)
		
class UserSubmission(models.Model):
	User = models.ForeignKey(User,on_delete= models.CASCADE)
	question = models.ForeignKey(CodeQuestion,on_delete= models.CASCADE)
	failed_testcase = models.TextField(blank=True,null=True)
	expected_output = models.TextField(blank=True,null=True)
	user_output = models.TextField(blank=True,null=True)
	ith_test_case_failed = models.IntegerField(blank=True,null=True)
	rmin = models.IntegerField()
	rsec = models.IntegerField()

Skillet/coding/views.py
from django.shortcuts import render

from django.http import HttpResponse ,HttpResponseRedirect
from django.urls import reverse

from .models import *
from login.models import UserProfile


from quiz.models import Question
from django.core.files import File

# Create your views here.

def first_question():
    list = Question.objects.all()
    list = list[0]
    return list

def last_question():
    list = Question.objects.all()
    len_lst = len(list)
    list = list[len_lst-1]
    return list


def find_wrong_line(correct_file_list,user_file_list):
		#print correct_file_list
	if len(correct_file_list) > len(user_file_list):
		return -2
	for i in range(0,len(correct_file_list)):
		user_line = user_file_list[i].rstrip('\n')
		correct_line = correct_file_list[i].rstrip('\n')
		#print 'userline '+user_line
		#print 'correct_line '+correct_line
		if correct_line != user_line:
			# print correct_line+" expexted this "+ " but got "+user_line
			return i
	return -1

def calculate_wrong(request,question,code,wrong_line,correct_file_list,user_file_list):
	lines_per_testcase = code.lines_per_testcase
	lines_per_answer = code.lines_per_answer
	testcase_file = code.testcase_file
	
	#testcase number failed,+1 for 0-indexing
	ith_test_case_failed = (wrong_line/lines_per_answer)+1

	
	# file open
	testcase_file.open('r')
	testcase_file_list = testcase_file.readlines()
	testcase_file.close()
	# file close

	testcase_start = (lines_per_testcase*(ith_test_case_failed-1))+1
	testcase_end = testcase_start + lines_per_testcase
	
	failed_testcase = str()
	for x in testcase_file_list[testcase_start:testcase_end]:
		failed_testcase += x

	output_start = lines_per_answer*(ith_test_case_failed-1)
	output_end = output_start+lines_per_answer
	
	user_output = str()
	for x in user_file_list[output_start:output_end]:
		user_output +=x

	expected_output = str()
	for x in correct_file_list[output_start:output_end]:
		expected_output +=x 
	rmin = request.POST['min']
	rsec = request.POST['sec']
	submit  = UserSubmission.objects.create(User=request.user,question=question,failed_testcase=failed_testcase,expected_output=expected_output,user_output=user_output,ith_test_case_failed=ith_test_case_failed,rmin=rmin,rsec=rsec)	
	submit.save()


# will hit only on post
def answer_coding(request,pk,question):
	code = CodeQuestionExtend.objects.get(question=question)

	correct_file = code.answer_file	

	# file open
	correct_file.open(mode='r')
	correct_file_list = correct_file.readlines()
	correct_file.close()
	# file close

	user_file_list = request.FILES['userAnswer'].readlines()
	
	rmin = request.POST['min']
	rsec = request.POST['sec']

	wrong_line = find_wrong_line(correct_file_list,user_file_list)
	if wrong_line == -2:
		# dic['message'] = "some testcases are missing"
		submit = UserSubmission.objects.create(question=question,User=request.user,ith_test_case_failed=-2,rmin=rmin,rsec=rsec)
		submit.save()
	elif wrong_line != -1:
		calculate_wrong(request,question,code,wrong_line,correct_file_list,user_file_list)
	else:
		status = CodeUserStatus.objects.get(question=question,User=request.user)
		status.question_status = "Accepted"
		status.rmin = rmin
		status.save()
		submit  = UserSubmission.objects.create(User=request.user,question=question,ith_test_case_failed=-1,rmin=rmin,rsec=rsec)
		submit.save()
	return coding_display(request,pk,question)
	
def coding_display(request,pk,question):
	if request.method == 'GET':
		current_status = CodeUserStatus.objects.get(User=request.user,question=question)
		user = UserProfile.objects.get(user =request.user)
		code = CodeQuestionExtend.objects.get(question=question)
		testcase = CodeTestCase.objects.filter(question=question)
		user_submission  = UserSubmission.objects.filter(User=request.user,question=question).order_by('-pk')
		is_not_first_question = False
		islast_question = False
		if question != first_question():
			is_not_first_question = True
		if question == last_question():
			islast_question = True
		dic ={
		'question' : question,
		'code' :code,
		'testcase' : testcase,
		'current_status' : current_status,
		'last_question' : islast_question,
		'is_not_first_question' : is_not_first_question,
		'user' : user,
		'user_submission' : user_submission,
		}
		return render(request,'coding/index.html',dic)
	else:
		return HttpResponseRedirect(reverse('quiz:disp',args = (question.id,)))

def submission(request,pk,question):
	user_submission  = UserSubmission.objects.get(pk=pk,question=question)
	if user_submission.User == request.user:
		failed_testcase = str(user_submission.failed_testcase)
		failed_testcase = failed_testcase.strip("[']")
		failed_testcase = failed_testcase.split(',')
		print(failed_testcase)
		dic = {
		'ith_test_case_failed' : user_submission.ith_test_case_failed,
		'wrong_testcase' : failed_testcase,
		'expected_output' : user_submission.expected_output,
		'user_output' 	  : user_submission.user_output
		}
		return render(request,'coding/submission.html',dic)
		return HttpResponse("hi")
	else:
		return HttpResponse("You dont own this submission")

Skillet/coding/templates/coding/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Skill-let</title>

      <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
      <meta name = "viewport" content = "width = device-width, initial-scale = 1">
      
      <script src=" {% static "quiz/js/jquery-1.11.1.min.js" %} " ></script>

    <script src=" {% static "quiz/js/bootstrap.min.js" %} "></script>
{% block head %}
 {% endblock %}

    </head>
        {% block content %}
        {% endblock %}
    </html>

Skillet/coding/templates/coding/index.html
{% extends "coding/base.html" %}
{% load static %}

{% block head %}
	
	{# timer #}
	<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="{% static 'quiz/js/jquery.countdownTimer.min.js'  %}"></script>
	{# end timer #}
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/clear.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/roundbox.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/problem-statement.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/table-form.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/ttypography.css' %}">

<style type="text/css">
	.verdict-accepted {
	color: #0a0;
	font-weight: bold;
}
</style>

<script type="text/javascript">

function timer () {
	
	var x = document.getElementById('ms_timer');
	var min = document.getElementById('minrem');
	var sec = document.getElementById('secrem');
	min.value = x.textContent[0]+x.textContent[1];
	sec.value = x.textContent[3]+x.textContent[4];
	console.log(min.value+" " + sec.value);
}



$(function(){
$('#ms_timer').countdowntimer({
minutes : {{user.rmin}},
seconds : {{user.rsec}},
size : "lg",
expiryUrl : "/",
});
});

$("#form").submit(function(e) {
    e.preventDefault();
});


var csrfcookie = function() {
var cookieValue = null,
    name = 'csrftoken';
if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) == (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
        }
    }
}
return cookieValue;
};

var params = function () {
        timer()
        var ps = "min=" + document.getElementById('minrem').value+"&sec="+document.getElementById('secrem').value;
        //console.log(ps);
        return ps;
    }


setInterval(function(){ 
    
var data_file = "../../timer";
  var http_request = new XMLHttpRequest();

  http_request.open("POST", data_file, true);


  http_request.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  http_request.setRequestHeader('X-CSRFToken', csrfcookie());

  http_request.send(params());

}, 5000);

</script>



{% endblock head %}

{% block content %}
<body>
<div id="body">



	<div style="position : relative;">
			<!-- side bar start -->
		<div id="sidebar">
	<form id="form" class="submitForm" enctype="multipart/form-data" action="{% url 'quiz:disp' question.id %}" method="post" onsubmit="timer()">
	{% csrf_token %}
			<div class="roundbox sidebox">
			<div class="roundbox-lt">&nbsp;</div>
			<div class="roundbox-rt">&nbsp;</div>
			<div class="caption titled">
			→ Timer
   			 </div>
   			 <div>	
       			 <div class="countdowntimer col-md-8">
       			 <span style="font-size : 35px;color: black; margin-left = 10px;margin-left: 2em;" id="ms_timer" ></span>
  	</div>
			</div> 
		</div>

			{% if current_status.question_status == 'Not Accepted'%}				
			<!-- 1st side box start -->
			<div class="roundbox sidebox">
			<div class="roundbox-lt">&nbsp;</div>
			<div class="roundbox-rt">&nbsp;</div>
			<div class="caption titled">
			→ Submit?
   			 </div>
   			 <div>	
       			<table class="table-form" style="width:90%;">
			    <tbody>
			    	<tr>
			    		<td class="field">Get input file</td>
			    		<td>
			    			<a target="_blank" class="submit"style="color:black;" href="{{code.testcase_file.url}}">Download inputs</a>
			    		</td>
			    	</tr>
			        <tr>
			            <td class="field">Choose file:</td>
			            <td>
			                <input name="userAnswer"  type="file">
			            </td>
			        </tr>
			        <tr>
			            <td colspan="2">
			                <div style="text-align: center;">
			                    <div style="position: relative; display: inline-block;">
			                            <input style="width:10em;" class="submit" name="nav" value="submit" type="submit">
			                    </div>
			                </div>
			            </td>
			        </tr>
			    </tbody>
				</table>
			</div> 
		</div>
			<!-- 1st side box end -->
		{% else %}
		<!-- 1st side box end -->
		<div class="roundbox sidebox">
			<div class="roundbox-lt">&nbsp;</div>
			<div class="roundbox-rt">&nbsp;</div>
			<div class="caption titled">
			→ Result
   			 </div>
   			 <div style="margin-left: 6em;">	
       			Accepted
			</div> 
		</div>
<!-- 1st side box end -->
{% endif %}


		<!-- 2nd side box start -->
			<div class="roundbox sidebox">
			<div class="roundbox-lt">&nbsp;</div>
			<div class="roundbox-rt">&nbsp;</div>
			<div class="caption titled">
			→ Navigation
   			 </div>
   			 <div>	
       			 <table class="table-form" style="width:90%;">
			    <tbody>
			        <tr>
			            {% if is_not_first_question %}
			            <td class="field">
			            <input style="width:10em;" class="submit" name="nav" value="Previous" type="submit"></td>
			            {% endif %}
			            <td>
							{% if last_question %}
			               <input id="finish"  style="width:10em;" class="submit" name="nav" value="Finish" type="submit">
							{% else %}
			               <input style="width:10em;" class="submit" name="nav" value="Next" type="submit">
			            	{% endif %}
			            </td>
			        </tr>
			    </tbody>
				</table>
				<input id="minrem" name="min" value="{{user.rmin}}" type="hidden">
				<input id="secrem" name="sec" value="{user.rsec}}" type="hidden">
				<input id="Qstatus" name="Qstatus" value="red" type="hidden">
				</form>
			</div> 
		</div>
			<!-- 2nd side box end -->

			<!-- submission box -->
		<div class="roundbox sidebox" style="">
            <div class="roundbox-lt">&nbsp;</div>
            <div class="roundbox-rt">&nbsp;</div>
        <div class="caption titled">→ Last submissions
            <div class="top-links">
            </div>
        </div>
        <table class="rtable smaller">
            <tbody>
            <!-- heading table-->
                <tr>
                    <th class="left " style="width:2.5em;">Submission</th>
                    <th class=" " style="width:7em;">Time</th>
                            <th class=" ">Verdict</th>
                </tr>
                <!-- heading table end -->
                    
                {% for x in user_submission %}
                	
                	{% if forloop.counter|divisibleby:2 == 1 %}
                	<tr>
                        <td class="left  dark ">
                        <a target="_blank" href="{% url 'code:submission' x.id x.question.id  %}">{{x.id}}</a>
                        </td>
                            <td class=" dark ">{{x.rmin}}:{{x.rsec}}</td>
                            <td class=" dark ">
                            {% if x.ith_test_case_failed != -1 %}
                        	<span class="verdict-rejected">Wrong answer on test</span>
                            <span class="verdict-format-judged">{{x.ith_test_case_failed}}</span>
                        	</td>
                            {% else %}
                            <span class="verdict-accepted">Accepted</span>
                        	{% endif %}
                            </td>
                    </tr>
                    {% else %}
                    <tr>
                         <td class="left bottom ">
                         <a target="_blank" href="{% url 'code:submission' x.id x.question.id  %}">{{x.id}}</a></td>
                        <td class="bottom ">{{x.rmin}}:{{x.rsec}}</td>
                        <td class="bottom ">
                        	{% if x.ith_test_case_failed != -1 %}
                        	<span class="verdict-rejected">Wrong answer on test</span>
                            <span class="verdict-format-judged">{{x.ith_test_case_failed}}</span>
                            {% else %}
                            <span class="verdict-accepted">Accepted</span>
                        	{% endif %}
                        </td>
                    </tr>
                	{% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
			<!-- submission box -->

		</div>
			<!--  side bar end -->

<!-- leftbox start -->
<div id="pageContent" class="content-with-sidebar">
	<div class="problemindexholder">
		<div class="problem-statement">
		<div class="ttypography">
			<div class="header">
				<div class="title">{{question.question_text}}</div>
			</div>
			<div>
				{% autoescape off %}
				{{code.problem_statement}}
				{% endautoescape %}
			</div>
<div class="input-specification">
<div class="section-title">Input</div>
	{{ code.input_statement |safe }}
</div>

<div class="output-specification">
<div class="section-title">Output</div>
{{ code.output_statement | safe }}
</div>

<!-- constraint start -->
<div class="note">
<div class="section-title">Constraint</div>
{{ code.constraint | safe }}
</div>
<!-- constraint end -->



<div class="sample-tests">
<div class="section-title">Examples</div>
<div class="sample-test">

{% for x in testcase %}
		
	<div class="input">
		<div class="title">Input</div>
			<pre>{{ x.input }}</pre>
	</div>
	<div class="output">
		<div class="title">Output</div>
			<pre>{{ x.output }}</pre>
	</div>

{% endfor %}	

</div>
<!-- sample-test end -->
</div>
<!-- sample-tests end -->

<!-- Explanation start -->
<div class="note">
<div class="section-title">Explanation</div>
{{ code.explanation | safe }}
</div>
<!-- Explanation end -->


{% if message %}
	
<div class="sample-tests">
<div class="section-title">Result</div>
		<div class="sample-test">
		<div class="input">
			{# <div class="title">Result</div> #}
			<pre>{{ message }}</pre>
		</div>
		</div>
<div>

{% endif %}


{% if message == 'wrong answer' %}
<br>
<div class="sample-tests">
<div class="section-title">Failed on testcase {{testcase_failed}} </div>
<div class="sample-test">

	<div class="input">
		{# <div class="title">&nbsp;</div> #}
			<pre>
			{% for x in wrong_testcase %}
			{{x}}<br>
			{% endfor %}</pre>
	</div>

</div>
<!-- failed-test end -->
</div>

<div class="section-title">&nbsp;</div>
<div class="sample-test">
<div class="input">
		<div class="title">Your Output</div>
			<pre>{% for x in user_output %}{{x}}{% endfor %}</pre>
	</div>

	<div class="output">
		<div class="title">Expected Output</div>
			<pre>{% for x in expected_output %}{{x}}{% endfor %}</pre>
	</div>
</div>

</div>
</div>
{% endif %}
{# wrong answer end #}
		<!-- ttypography end-->
	</div>
		<!-- problem-statement end -->
	
	</div>	
	<!-- problem holder end -->
</div>
	<!-- leftbox end-->
	</div>
</div>
<!-- id body end -->
</body>
{% endblock content %}

Skillet/coding/templates/coding/submission.html
{% extends "coding/base.html" %}
{% load static %}

{% block head %}
	
	{# timer #}
	<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="{% static 'quiz/js/jquery.countdownTimer.min.js'  %}"></script>
	{# end timer #}
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/clear.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/roundbox.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/problem-statement.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/table-form.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'coding/css/ttypography.css' %}">

{% endblock head %}

{% block content %}
	<div id="body">



	<div style="position : relative;">
			<!-- side bar start -->
		<div id="sidebar">
	</div>
			<!--  side bar end -->

<!-- leftbox start -->
<div id="pageContent" class="content-with-sidebar">
	<div class="problemindexholder">
		<div class="problem-statement">
		<div class="ttypography">



<div class="sample-tests">
<div class="section-title">Failed on testcase {{ith_test_case_failed}} </div>
<div class="sample-test">

	<div class="input">
		{# <div class="title">&nbsp;</div> #}
			<pre>{% for x in wrong_testcase %}{{x}}{% endfor %}</pre>
	</div>

</div>
<!-- failed-test end -->
</div>



<div class="sample-tests">
<div class="section-title">&nbsp;</div>
<div class="sample-test">
<div class="input">
		<div class="title">Your Output</div>
			<pre>{% for x in user_output %}{{x}}{% endfor %}</pre>
	</div>

	<div class="output">
		<div class="title">Expected Output</div>
			<pre>{% for x in expected_output %}{{x}}{% endfor %}</pre>
	</div>
</div>
</div>
</div>

		<!-- ttypography end-->
	</div>
		<!-- problem-statement end -->
	
	</div>	
	<!-- problem holder end -->
</div>
	<!-- leftbox end-->
	</div>
</div>
<!-- id body end -->


    </div>
{%	endblock %}